version: '3.7'
services:
  cs2-servu:
    build: .
    container_name: cs2-dedicated
    environment:
      - SRCDS_TOKEN
      - STEAMAPPVALIDATE
      - CS2_SERVERNAME
      - CS2_CHEATS
      - CS2_PORT
      - CS2_SERVER_HIBERNATE
      - CS2_RCON_PORT
      - CS2_LAN
      - CS2_RCONPW
      - CS2_PW
      - CS2_MAXPLAYERS
      - CS2_ADDITIONAL_ARGS
      - CS2_CFG_URL
      # Game modes
      - CS2_GAMEALIAS
      - CS2_GAMETYPE
      - CS2_GAMEMODE
      - CS2_MAPGROUP
      - CS2_STARTMAP
      # Bots
      - CS2_BOT_DIFFICULTY
      - CS2_BOT_QUOTA
      - CS2_BOT_QUOTA_MODE
      # TV
      - TV_AUTORECORD
      - TV_ENABLE
      - TV_PORT
      - TV_PW
      - TV_RELAY_PW
      - TV_MAXRATE
      - TV_DELAY
      # Logs
      - CS2_LOG
      - CS2_LOG_MONEY
      - CS2_LOG_DETAIL
      - CS2_LOG_ITEMS
    volumes:
      - cs2:/home/steam/cs2-dedicated/  # Persistent data volume mount point inside container
    ports:
      - "27015:27015/tcp"           # TCP
      - "27015:27015/udp"           # UDP
      - "27020:27020/udp"           # UDP
    stdin_open: true # Add local console for docker attach, docker attach --sig-proxy=false cs2-dedicated
    tty: true # Add local console for docker attach, docker attach --sig-proxy=false cs2-dedicated
volumes:
  cs2:
